server:
  port: 8081
spring:
  application:
    name: recipes
  profiles:
    active: dev
  datasource:
    password: dev
    url: jdbc:h2:file:./db/${ACTIVE_PROFILE:dev}/${DEV_DBNAME:demodb}
    username: dev
    driverClassName: org.h2.Driver
    h2:
      console:
        enabled: true
        path: /h2
        settings:
          web-allow-others: true
    jpa:
      open-in-view: false
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
        use-new-id-generator-mappings: true
      properties:
        hibernate:
          format_sql: true
          order_inserts=true:
          jdbc:
            batch_size=4:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    zipkin:
      base-url: http://localhost:9411
    rabbitmq:
      addresses: localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true